name: Deploy to Cloud Run

on:
  workflow_dispatch:   # Manual trigger
  push:
    branches: ["main" , "de"] # Optional: deploy on push to main

env:
  PROJECT_ID: todoolist-2025
  REGION: us-central1
  REPO_NAME: todo-repo
  SERVICE_NAME: todo-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # -------------------------
    # 1. Checkout code
    # -------------------------
    - name: Checkout code
      uses: actions/checkout@v3

    # -------------------------
    # 2. Authenticate to GCP
    # -------------------------
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}   # <--- Add your GCP JSON key in GitHub secrets

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    # -------------------------
    # 3. Authenticate Docker
    # -------------------------
    - name: Configure Docker
      run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    # -------------------------
    # 4. Build & Push image
    # -------------------------
    - name: Build and Push Docker image
      working-directory: TodoListFirebaseApp   # 👈 where Dockerfile is
      run: |
        IMAGE="us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/todo-api:${{ github.sha }}"
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV
        docker build -t $IMAGE .
        docker push $IMAGE
    
    - name: Deploy to Cloud Run # --set-env-vars=FIREBASE_SERVICE_ACCOUNT_KEY_BASE64="${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_BASE64 }}"
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image "us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/todo-api:${{ github.sha }}" \
          --region ${{ env.REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --update-secrets=FIREBASE_SERVICE_ACCOUNT_KEY=secrets.GCP_SA_KEY:latest



